### ISSUE TITLE
클래스 용도별로 package  를 분리하세요

### ISSUE THREAD

**Issue by callor** [hykim6856/Biz-2023-11-505-java#1]
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/23270330/ae7e06d5-21d4-43e5-95e6-11a211e300ef)

모든 클래스가 com.callor.scores base-package 에 들어 있네요
각 클래스가 하는 일을 구분하여 package 를 분리하세요

**Comment by hykim6856** [comment]
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/151485951/754f1e80-e9f4-46b3-bc27-6336256bd0fa)
각 클래스가 하는 일을 기준으로 package 분리 수정완료하였습니다.
