### ISSUE TITLE
main() 에서는 scoreService.creScore(); 를 한번만 호출

### ISSUE THREAD

**Issue by callor** [hykim6856/Biz-2023-11-505-java#2]
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/23270330/7fde5277-ab0d-46cf-a4c2-5ee9046ff654)

main() 에서는 scoreService.creScore() 를 한번만 호출하고
creScore() method 에서 10명의 학생 성적을 생성해야 합니다

**Comment by hykim6856** [comment]
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/151485951/65a61355-06c0-4eb4-8916-87b8b38956c5)
main() 부분에서 for문 부분을 scoreService.creScore()안으로 넣었고, 학생 수는 main에서 지정하고 싶어서 매개변수로 따로 반복할 학생수를 지정할수 있도록 수정하였습니다. 
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/151485951/56ef92d9-2ad6-4f72-b107-03aa04cf877a)
만약 학생수도 scoreService.creScore()안에서 지정해야한다면 for문 밖에 int 변수를 선언하여 수정하겠습니다.
