### ISSUE TITLE
무슨일을 하는 코드 일까요

### ISSUE THREAD

**Issue by callor** [hykim6856/Biz-2023-11-505-java#4]
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/23270330/d51766dd-7be1-4fe3-8ee4-aa9c3ac55447)

위 이미지의 코드가 하는 일이 뭘까요
평균이 잘 계산 되나요?

**Comment by hykim6856** [comment]
scores.size는 과목별 점수의 합계에서 학생 수로 나눌때  학생 수가 변할때마다 scores 리스트의 크기를 세서 그에 맞는 수로 나뉠수 있도록 한것입니다.
![image](https://github.com/hykim6856/Biz-2023-11-505-java/assets/151485951/b8a92fad-036f-4224-b6af-a82a31a25df3)
좀더 식에 대해 식별을 용이하게 하고 불필요한 식이 반복됨을 방지하기 위해서 식을 사용하기 전 변수로 선언하여 식을 정리했습니다.

avgAvg 의 경우에는 학생별 평균을 구하기 위해 식이 반복되는걸 이용해서 처음 나왔던 이전 평균값에 지금 평균값을 더하고 그것을 학생수로 나누어서 평균의 평균값을 계산하는 식이었습니다.
 다시보니 그렇게 하기 위해서는 반복문 바깥에 float 형 변수 avgSum 를 먼저 선언하고
avgSum+= dto.getAvg()를하고 그 밑에 avgAvg= avgSum/ scores.size(); 를 했었어야 제대로 계산되는것 같습니다.

다만, 문제를 다시 읽으니 학생별 평균이 아닌 과목별 평균을 구하는 문제 인 것 같아. 첨부드린 사진 대로 수정하였습니다.
(사진에는 나와있지 않지만, 평균을 구하는 식은 반복문 바깥에 꺼내두는게 좋을것 같아 반복문 바깥으로 이동하여 수정하였습니다.)
